package org.l2jmobius.gameserver.fakeplayer.model.enums;

public enum FpcSocialEpisodeType
{
	PLEASANT_CHAT,
	PARTY_INVITE_REQUESTED,
	PARTY_INVITE_ACCEPTED,
	PARTY_INVITE_DECLINED,
	BUFFED_ME,
	HELPED_ME,
	REVIVED_ME,
	ATTACKED_ME,
	WITNESSED_PK,
	SPAMMED_REQUESTS,
	INSULTED_ME,
	THREATENED_ME,
	DISTRUSTED_ME,
	ATTACKED_BELIEFS,
	APOLOGIZED,
	THANKED_ME,
	EXPRESSED_RESPECT,
	PRAISED_ME,
	EXPRESSED_AFFECTION,
	REASSURED_ME,
	EXPRESSED_HATE,
	SOUGHT_REPAIR,
	ABANDONED_ME,
	KILLED_ME
}
